package message

// MessageType 消息类型
type MessageType = string

const (
	// ORDER_PAY 1688交易付款（卖家视角）
	ORDER_PAY MessageType = "ORDER_PAY"
	// ORDER_ANNOUNCE_SENDGOODS 1688订单发货（卖家视角）
	ORDER_ANNOUNCE_SENDGOODS MessageType = "ORDER_ANNOUNCE_SENDGOODS"
	// ORDER_BUYER_VIEW_PART_PART_SENDGOODS 1688订单部分发货（买家视角）/Partial delivery of 1688 order (buyer view)
	ORDER_BUYER_VIEW_PART_PART_SENDGOODS MessageType = "ORDER_BUYER_VIEW_PART_PART_SENDGOODS"
	// ORDER_BUYER_VIEW_ANNOUNCE_SENDGOODS 1688订单发货（买家视角）/1688 order delivery (buyer view)
	ORDER_BUYER_VIEW_ANNOUNCE_SENDGOODS MessageType = "ORDER_BUYER_VIEW_ANNOUNCE_SENDGOODS"
	// ORDER_BUYER_VIEW_ORDER_COMFIRM_RECEIVEGOODS 1688订单确认收货（买家视角）/order receipt confirmation (buyer view)
	ORDER_BUYER_VIEW_ORDER_COMFIRM_RECEIVEGOODS MessageType = "ORDER_BUYER_VIEW_ORDER_COMFIRM_RECEIVEGOODS"
	// ORDER_BUYER_VIEW_ORDER_SUCCESS 1688交易成功（买家视角）
	ORDER_BUYER_VIEW_ORDER_SUCCESS MessageType = "ORDER_BUYER_VIEW_ORDER_SUCCESS"
	// ORDER_BUYER_VIEW_ORDER_BUYER_CLOSE 1688买家关闭订单（买家视角）/buyer closing order (buyer view)
	ORDER_BUYER_VIEW_ORDER_BUYER_CLOSE MessageType = "ORDER_BUYER_VIEW_ORDER_BUYER_CLOSE"
	// ORDER_BUYER_VIEW_ORDER_BUYER_REFUND_IN_SALES 订单售中退款（买家视角）
	ORDER_BUYER_VIEW_ORDER_BUYER_REFUND_IN_SALES MessageType = "ORDER_BUYER_VIEW_ORDER_BUYER_REFUND_IN_SALES"
	// ORDER_BUYER_VIEW_ORDER_REFUND_AFTER_SALES 1688订单售后退款（买家视角）
	ORDER_BUYER_VIEW_ORDER_REFUND_AFTER_SALES MessageType = "ORDER_BUYER_VIEW_ORDER_REFUND_AFTER_SALES"
	// PRODUCT_RELATION_VIEW_PRODUCT_DELETE 1688产品删除（关系用户视角）
	PRODUCT_RELATION_VIEW_PRODUCT_DELETE MessageType = "PRODUCT_RELATION_VIEW_PRODUCT_DELETE"
	// PRODUCT_RELATION_VIEW_PRODUCT_EXPIRE 1688产品下架（关系用户视角）
	PRODUCT_RELATION_VIEW_PRODUCT_EXPIRE MessageType = "PRODUCT_RELATION_VIEW_PRODUCT_EXPIRE"
	// PRODUCT_RELATION_VIEW_PRODUCT_NEW_OR_MODIFY 1688产品新增或修改（关系用户视角）
	PRODUCT_RELATION_VIEW_PRODUCT_NEW_OR_MODIFY MessageType = "PRODUCT_RELATION_VIEW_PRODUCT_NEW_OR_MODIFY"
	// PRODUCT_RELATION_VIEW_PRODUCT_REPOST 1688产品上架（关系用户视角）
	PRODUCT_RELATION_VIEW_PRODUCT_REPOST MessageType = "PRODUCT_RELATION_VIEW_PRODUCT_REPOST"
	// PRODUCT_PRODUCT_INVENTORY_CHANGE 1688商品库存变更消息
	PRODUCT_PRODUCT_INVENTORY_CHANGE MessageType = "PRODUCT_PRODUCT_INVENTORY_CHANGE"
	// PRODUCT_RELATION_VIEW_EXIT_SUPERBUYER 商品池&超买价变更消息
	PRODUCT_RELATION_VIEW_EXIT_SUPERBUYER MessageType = "PRODUCT_RELATION_VIEW_EXIT_SUPERBUYER"
	// PRODUCT_RELATION_VIEW_PRODUCT_AUDIT 1688产品审核下架（关系用户视角）
	PRODUCT_RELATION_VIEW_PRODUCT_AUDIT MessageType = "PRODUCT_RELATION_VIEW_PRODUCT_AUDIT"
	// LOGISTICS_BUYER_VIEW_TRACE 物流单状态变更（买家视角）
	LOGISTICS_BUYER_VIEW_TRACE MessageType = "LOGISTICS_BUYER_VIEW_TRACE"
	// LOGISTICS_MAIL_NO_CHANGE 物流单号修改消息
	LOGISTICS_MAIL_NO_CHANGE MessageType = "LOGISTICS_MAIL_NO_CHANGE"
)

// RefundAction 退款操作
type RefundAction = string

const (
	// BUYER_APPLY_REFUND 买家申请退款
	BUYER_APPLY_REFUND RefundAction = "BUYER_APPLY_REFUND"
	// BUYER_RECEIVE_CLOSE 买家确认收货关闭
	BUYER_RECEIVE_CLOSE RefundAction = "BUYER_RECEIVE_CLOSE"
	// SELLER_SEND_GOODS_CLOSE 卖家发货关闭
	SELLER_SEND_GOODS_CLOSE RefundAction = "SELLER_SEND_GOODS_CLOSE"
	// BUYER_CANCEL_REFUND_CLOSE 买家撤销退款申请关闭
	BUYER_CANCEL_REFUND_CLOSE RefundAction = "BUYER_CANCEL_REFUND_CLOSE"
	// BUYER_UPLOAD_BILL 买家上传凭证
	BUYER_UPLOAD_BILL RefundAction = "BUYER_UPLOAD_BILL"
	// SELLER_UPLOAD_BILL 卖家上传凭证
	SELLER_UPLOAD_BILL RefundAction = "SELLER_UPLOAD_BILL"
	// SELLER_REJECT_REFUND 卖家拒绝退款
	SELLER_REJECT_REFUND RefundAction = "SELLER_REJECT_REFUND"
	// SELLER_AGREE_REFUND 卖家同意退款
	SELLER_AGREE_REFUND RefundAction = "SELLER_AGREE_REFUND"
	// SELLER_RECEIVE_GOODS 卖家确认收货
	SELLER_RECEIVE_GOODS RefundAction = "SELLER_RECEIVE_GOODS"
	// BUYER_SEND_GOODS 买家声明发货
	BUYER_SEND_GOODS RefundAction = "BUYER_SEND_GOODS"
	// BUYER_MODIFY_REFUND_PROTOCOL 买家修改退款协议
	BUYER_MODIFY_REFUND_PROTOCOL RefundAction = "BUYER_MODIFY_REFUND_PROTOCOL"
	// BUYER_APPLY_SUPPORT 买家申请客服介入
	BUYER_APPLY_SUPPORT RefundAction = "BUYER_APPLY_SUPPORT"
	// SELLER_APPLY_SUPPORT 卖家申请客服介入
	SELLER_APPLY_SUPPORT RefundAction = "SELLER_APPLY_SUPPORT"
	// SYSTEM_AGREE_REFUND_PROTOCOL 系统超时同意退款协议
	SYSTEM_AGREE_REFUND_PROTOCOL RefundAction = "SYSTEM_AGREE_REFUND_PROTOCOL"
	// SYSTEM_AGREE_REFUND 系统超时同意退款
	SYSTEM_AGREE_REFUND RefundAction = "SYSTEM_AGREE_REFUND"
	// SYSTEM_SEND_GOODS 系统超时退货，主交易流程的退货
	SYSTEM_SEND_GOODS RefundAction = "SYSTEM_SEND_GOODS"
	// SYSTEM_MODIFY_REFUND_PROTOCOL 系统超时修改协议
	SYSTEM_MODIFY_REFUND_PROTOCOL RefundAction = "SYSTEM_MODIFY_REFUND_PROTOCOL"
	// SYSTEM_NOTIFY_APPLY_SUPPORT 系统通知申请客服介入
	SYSTEM_NOTIFY_APPLY_SUPPORT RefundAction = "SYSTEM_NOTIFY_APPLY_SUPPORT"
	// SELLER_AGREE_REFUND_PROCOTOL 卖家同意退款协议
	SELLER_AGREE_REFUND_PROCOTOL RefundAction = "SELLER_AGREE_REFUND_PROCOTOL"
	// SELLER_REJECT_REFUND_PROCOTOL 卖家拒绝退款协议
	SELLER_REJECT_REFUND_PROCOTOL RefundAction = "SELLER_REJECT_REFUND_PROCOTOL"
	// CRM_APPLY_TIMEOUT_CLOSE 申请客服介入、超时关闭、目前仅售后业务在用
	CRM_APPLY_TIMEOUT_CLOSE RefundAction = "CRM_APPLY_TIMEOUT_CLOSE"
	// CRM_APPLY_SUPPORT CRM申请介入
	CRM_APPLY_SUPPORT RefundAction = "CRM_APPLY_SUPPORT"
	// CRM_INTERVENE_TASK CRM介入处理
	CRM_INTERVENE_TASK RefundAction = "CRM_INTERVENE_TASK"
	// CRM_DISMISS_TASK CRM撤销工单
	CRM_DISMISS_TASK RefundAction = "CRM_DISMISS_TASK"
	// CRM_FINISH_TASK CRM完结工单
	CRM_FINISH_TASK RefundAction = "CRM_FINISH_TASK"
	// BUYER_STEP_PAY_ORDER_CLOSE 买家支付，退款关闭，分阶段订单情况
	BUYER_STEP_PAY_ORDER_CLOSE RefundAction = "BUYER_STEP_PAY_ORDER_CLOSE"
	// BUYER_STEP_CONFIRM_CLOSE 买家确认，退款关闭，分阶段订单情况
	BUYER_STEP_CONFIRM_CLOSE RefundAction = "BUYER_STEP_CONFIRM_CLOSE"
	// BUYER_CLOSE_TRADE_CLOSE 买家终止交易，退款关闭，分阶段订单情况
	BUYER_CLOSE_TRADE_CLOSE RefundAction = "BUYER_CLOSE_TRADE_CLOSE"
	// SELLER_CONFIRM_ORDER_CLOSE 卖家确认，退款关闭，分阶段订单情况
	SELLER_CONFIRM_ORDER_CLOSE RefundAction = "SELLER_CONFIRM_ORDER_CLOSE"
	// SELLER_STEP_PUSH_CLOSE 卖家推进，退款关闭，分阶段订单情况
	SELLER_STEP_PUSH_CLOSE RefundAction = "SELLER_STEP_PUSH_CLOSE"
)

// Operator 操作的发起人
type Operator = string

const (
	// BUYER 买家
	BUYER Operator = "buyer"
	// SELLER 卖家
	SELLER Operator = "seller"
	// SYSTEM 系统
	SYSTEM Operator = "system"
)

// ProductMessageStatus 消息类型，具体可为
type ProductMessageStatus = string

const (
	RELATION_VIEW_PRODUCT_EXPIRE        ProductMessageStatus = "RELATION_VIEW_PRODUCT_EXPIRE"
	RELATION_VIEW_PRODUCT_NEW_OR_MODIFY ProductMessageStatus = "RELATION_VIEW_PRODUCT_NEW_OR_MODIFY"
	RELATION_VIEW_PRODUCT_DELETE        ProductMessageStatus = "RELATION_VIEW_PRODUCT_DELETE"
	RELATION_VIEW_PRODUCT_REPOST        ProductMessageStatus = "RELATION_VIEW_PRODUCT_REPOST"
)

// ProductStatus 商品状态
type ProductStatus = string

const (
	// ProductStatus_DELETE 删除商品, 商品不在商品池
	ProductStatus_DELETE ProductStatus = "DELETE"
	// ProductStatus_UPDATE 商品超买价状态可能有更新
	ProductStatus_UPDATE ProductStatus = "UPDATE"
)

// LogisticsStatus 物流单发生变化的状态
type LogisticsStatus = string

const (
	// Logistics_CONSIGN 发货
	Logistics_CONSIGN LogisticsStatus = "CONSIGN"
	// Logistics_ACCEPT 揽收
	Logistics_ACCEPT LogisticsStatus = "ACCEPT"
	// Logistics_TRANSPORT 运输
	Logistics_TRANSPORT LogisticsStatus = "TRANSPORT"
	// Logistics_DELIVERING 派送
	Logistics_DELIVERING LogisticsStatus = "DELIVERING"
	// Logistics_SIGN 签收
	Logistics_SIGN LogisticsStatus = "SIGN"
)
